spring:
  config:
    activate:
      on-profile: "test"

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  # for test
  h2:
    console:
      enabled: true
  datasource:
    # for test
    url: jdbc:h2:./compono-test;MODE=MYSQL;DB_CLOSE_DELAY=-1;
    username: sa
    password: 1234
    hikari:
      maximum-pool-size: 5

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # for test
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true # for test
    show-sql: true # for test
