spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 20
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      default_batch_fetch_size: 1000
      hibernate:
        format_sql: false
        show_sql: false