spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      default_batch_fetch_size: 1000
      hibernate:
        format_sql: false
        show_sql: false